server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
    DriverName: com.mysql.jdbc.Driver
  application:
    name: user-service # 应用名称
mybatis:
  type-aliases-package: com.vplus.demo.userservice.models.pojo
logging:
  level:
    com.vplus.demo.userservice.models.mapper: debug
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    register-with-erueka: true
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    #服务失效时间，默认值90秒
    lease-expiration-duration-in-seconds: 90
    #服务续约(renew)的间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${server.port}
